---
sudo: required
dist: trusty
language: node_js
node_js:
  - 6
before_install:
    - "npm install -g yarn"
install:
  - yarn install
cache:
  directories:
    - node_modules
    - $HOME/.fancyuicache
  yarn: true
after_script:
  - npm run coverage