---
sudo: required
dist: trusty
language: node_js
node_js:
  - 6
before_install:
    - "yarn --version"
install:
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.fancyuicache
  
after_script:
  - npm run coverage